config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments, only: [:create, :destroy]
  resources :likes, only: [:create]
  # root 'pages/hello'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end
  namespace :api do
    namespace :v1 do
      post 'users/sign_in' => 'users#login'
      get 'posts' => 'posts#index'
      get 'comments' => 'comments#index'
      post 'comments/create' => 'comments#create'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments
  validates :title, presence: true, length: { minimum: 0, maximum: 250 }
  validates :text, presence: true
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  after_save :increase_posts_counter

  def increase_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      def index
        user = User.find_by_id(1)
        respond_to do |format|
          if user
            format.json { render json: user.posts }
          else
            format.json { render json: { success: false, message: ['User must exist'] } }
          end
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @user = User.find(params[:user_id])
    @user_posts = Post.includes(:author, :likes, :comments).where(author_id: params[:user_id]).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
    @params = params
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'New post created successfully'
      redirect_to user_post_path(id: @post.id, user_id: @post.author_id)
    else
      render :new, status: :unprocessable_entity, content_type: 'text/html'
      headers['Content-Type'] = 'text/html'
      flash[:danger] = 'Post could not be created'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    authorize! :destroy, @post
    @comment = @post.comments
    @comment.each(&:destroy)
    @post.destroy
    flash[:success] = ['Post Deleted Successfully']

    respond_to do |format|
      format.html { redirect_to "/users/#{current_user.id}/posts" }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end
end

app/views/posts/index.html.erb
<%= render partial: 'partials/user_card', locals: { user: @user } %>

<% @user_posts.each do |post| %>
    <%= render partial: 'partials/post_snipet', locals: { post: post} %>
      <ul class="comments">
      <% post.recent_comments.each do |comment| %>
        <li><%= comment.author.name %>: <%= comment.text %>
      <% end %>
      </ul>
<% end %>


<%= link_to "Add new post", new_user_post_path(@user), class: "btn see-all-btn" %>

app/views/posts/new.html.erb
<h1>Create new post article</h1>
<%= form_for @post, url: user_posts_path do |f| %>
  <% if @post.errors.any? %>
    <ul class="errors">
      <% @post.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.hidden_field :author_id, value: @params ? @params['user_id'] : '' %>
  <div>
    <%= f.label :title %><br />
    <%= f.text_field :title, placeholder: 'Article title' %>
  </div>
  <div>
    <%= f.label :text, "Description" %><br />
    <%= f.text_area :text, placeholder: 'Type your article message in here...' %>
  </div>
  <%= f.submit "Submit post", disable_with: 'Submiting...' %>
<% end %>

app/views/posts/show.html.erb
<article class="post">
  <h3><%= @post.title %>  by <%= link_to @post.author.name, user_path(@post.author_id) %></h3>
  <div class="post-stats">
    <span>Comments <%= @post.comments_counter %> &nbsp;,&nbsp;</span>
    <span>Likes <%= @post.likes_counter %></span>
  </div>
  <p><%= @post.text %></p>
</article>
<%= form_for @like, url:likes_path do |f|%>
  <%= f.hidden_field :author_id, value: @post.author.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.submit "Like", disable_with: 'updating likes...' %>
<% end %>
<% if can? :destroy, @post %>
  <%= button_to "Delete", user_post_path(post_id: @post.id), method: :delete, data: {
    turbolinks: false,
  } %>
<% end %>
<br />
<ul class="comments">
  <% @post.recent_comments.each do |comment| %>
    <li>
      <%= comment.author.name %>: <%= comment.text %>
      <br>
      <% if can? :destroy, comment %>
        <%= button_to "Delete", comment_path(id: comment.id), method: :delete, data: {
          turbo: false,
        } %>
      <% end %>
    </li>
  <% end %>
</ul>
<h4>Add comment</h4>
<%= form_for @comment, url:comments_path do |f| %>
  <%= f.hidden_field :author_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.label :text %><br />
  <%= f.text_area :text, placeholder:'What are your thoughts on this post?' %><br />
  <%= f.submit "Submit comment", class:'btn', disable_with: 'Submiting Comment...' %>
<% end %>